FROM <imagen>:<versión> --> sirve para elegir a partir de qué imagen se basará nuestra nueva imagen

RUN <comando> --> sirve para ejecutar comandos de Linux dentro del contenedor, por ejemplo, para crear un directorio

COPY <ruta_anfitrión> <ruta_contenedor> --> copia los archivos que indiquemos desde nuestra computadora a la ruta que le indiquemos en el contenedor

EXPOSE <puerto> --> el puerto a exponer 

CMD [<comandos>] --> se ejecuta el comando que indiquemos. El comando debe estar en forma de array, por ejemplo CMD ["java","-jar","app.jar"]. Es el último comando a ejecutar en el dockerfile 

WORKDIR	<ruta> --> establece cual es el directorio dentro del contendor en donde se ejecutarán los próximos comandos

ENV <variable>=<valor> --> sirve para variables de entorno

ARG <argumento> --> es para argumentos que posteriormente se usan en el mismo dockerfile 	